apiVersion: v1
kind: Service
metadata:
  name: fastapi-demo
spec:
  selector:
    app: fastapi-deployment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8000
      nodePort: 30010
  type: NodePort